# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0029_auto_20170618_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_type',
            name='CODE',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='self_type',
            name='SNO',
            field=models.CharField(max_length=100),
        ),
    ]
