# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0048_auto_20170622_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='CONVERT',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='LATITUDE',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='details',
            name='LONGITUDE',
            field=models.CharField(max_length=5),
        ),
    ]
