# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0095_offender_dri_lic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='CAUSE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='DRIVER_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='DRUNK_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_CAUSE',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_DRIVER_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_REMARK',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_ROAD_ENGG_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_ROAD_ENV_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_VEC_MEH_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_VICTIM_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OTHER_WEATHER_COND_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OVER_SPEED_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='REMARKS',
        ),
        migrations.RemoveField(
            model_name='details',
            name='REMEDIES',
        ),
        migrations.RemoveField(
            model_name='details',
            name='ROAD_ENGG_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='ROAD_ENV_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='VEH_MECH_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='VICTIM_FAULT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='WEATHER_COND',
        ),
        migrations.AddField(
            model_name='collision',
            name='CAUSE',
            field=models.CharField(choices=[('KNOWN', 'Known'), ('UNKNOWN', 'Unknown')], default=0, max_length=15, verbose_name='Cause'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collision',
            name='DRIVER_FAULT',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.driver_fault', verbose_name='Fault of Driver'),
        ),
        migrations.AddField(
            model_name='collision',
            name='DRUNK_FAULT',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Case of Drunk Driving'),
        ),
        migrations.AddField(
            model_name='collision',
            name='OTHER_CAUSE',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Other Causes'),
        ),
        migrations.AddField(
            model_name='collision',
            name='OTHER_DRIVER_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Fault of Driver-Other'),
        ),
        migrations.AddField(
            model_name='collision',
            name='OTHER_REMARK',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Other Remarks'),
        ),
        migrations.AddField(
            model_name='collision',
            name='OTHER_ROAD_ENGG_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Road Engineering Fault - Other'),
        ),
        migrations.AddField(
            model_name='collision',
            name='OTHER_ROAD_ENV_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Road Environment Fault -Other'),
        ),
        migrations.AddField(
            model_name='collision',
            name='OTHER_VEC_MEH_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mechanical Fault -Other'),
        ),
        migrations.AddField(
            model_name='collision',
            name='OTHER_VICTIM_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Fault of Victim - Other'),
        ),
        migrations.AddField(
            model_name='collision',
            name='OTHER_WEATHER_COND_FAULT',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Weather Conditions - Other'),
        ),
        migrations.AddField(
            model_name='collision',
            name='OVER_SPEED_FAULT',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=15, verbose_name='Case of Overspeeding'),
        ),
        migrations.AddField(
            model_name='collision',
            name='REMARKS',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='collision',
            name='REMEDIES',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fir.remedies', verbose_name='Remedies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collision',
            name='ROAD_ENGG_FAULT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.road_engg_fault', verbose_name='Fault of Road Engineering'),
        ),
        migrations.AddField(
            model_name='collision',
            name='ROAD_ENV_FAULT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.road_env_fault', verbose_name='Fault of Road Environment'),
        ),
        migrations.AddField(
            model_name='collision',
            name='VEH_MECH_FAULT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.veh_mech_fault', verbose_name='Mechanical Fault of Vehicle'),
        ),
        migrations.AddField(
            model_name='collision',
            name='VICTIM_FAULT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.victim_fault', verbose_name='Fault of Victim'),
        ),
        migrations.AddField(
            model_name='collision',
            name='WEATHER_COND',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.weather_cond', verbose_name='Weather Conditions'),
        ),
    ]
